language: lisp
dist: xenial
sudo: required

git:
  depth: 3

env:
  matrix:
    #- LISP=abcl
    #- LISP=allegro
    - LISP=sbcl
    - LISP=ccl
    #- LISP=clisp
    #- LISP=ecl
    #- LISP=cmucl

addons:
  apt:
    packages: &standard_packages
    - python-numpy
    - python3-numpy

matrix:
  allow_failures:
    - env: LISP=clisp
    #- env: LISP=ccl

install:
  - ./install.sh
  #- curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash  
    
script:
  - cl -e "(in-package :cl-user)
           (ql:quickload :py4cl)
           (ql:quickload :py4cl/tests)

           (if (or
                 (let ((report (py4cl/tests:run)))
                   (when (or (plusp (slot-value report 'clunit::failed))
                             (plusp (slot-value report 'clunit::errors)))
                     (princ report)))
                 (let ((*config* ((PYCMD . \"python3\"))))
                   (let ((report (py4cl/tests:run)))
                     (when (or (plusp (slot-value report 'clunit::failed))
                               (plusp (slot-value report 'clunit::errors)))
                       (princ report)))))
                (uiop:quit 1))"
